package main
// generated by make bd
const btversion = "-X gofia.GitCommit=GOVVV-cf9373b -X gofia.GitBranch=GOVVV-master -X gofia.GitState=GOVVV-dirty -X gofia.GitSummary=GOVVV-cf9373b-dirty -X gofia.Version=GOVVV-0.0.0 -X gofia.BuildDate=GOVVV-2018-05-22T15:27:01Z"

const isandroid = true

