// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ths.proto

/*
Package thspbs is a generated protocol buffer package.

It is generated from these files:
	ths.proto

It has these top-level messages:
	Event
	Argument
	BaseInfo
	FriendInfo
	GroupInfo
	MemberInfo
	Message
	Messages
	EmptyReq
	HelloReq
	HelloResp
*/
package thspbs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MemberInfo_MemType int32

const (
	MemberInfo_UNKNOWN MemberInfo_MemType = 0
	MemberInfo_FRIEND  MemberInfo_MemType = 1
	MemberInfo_GROUP   MemberInfo_MemType = 2
	MemberInfo_PEER    MemberInfo_MemType = 3
)

var MemberInfo_MemType_name = map[int32]string{
	0: "UNKNOWN",
	1: "FRIEND",
	2: "GROUP",
	3: "PEER",
}
var MemberInfo_MemType_value = map[string]int32{
	"UNKNOWN": 0,
	"FRIEND":  1,
	"GROUP":   2,
	"PEER":    3,
}

func (x MemberInfo_MemType) String() string {
	return proto.EnumName(MemberInfo_MemType_name, int32(x))
}
func (MemberInfo_MemType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

type Event struct {
	EventId int64  `protobuf:"varint,1,opt,name=EventId" json:"EventId,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	// int32 NameId = 2;  // TODO
	Args     []string  `protobuf:"bytes,3,rep,name=Args" json:"Args,omitempty"`
	Margs    []string  `protobuf:"bytes,4,rep,name=Margs" json:"Margs,omitempty"`
	Uargs    *Argument `protobuf:"bytes,5,opt,name=Uargs" json:"Uargs,omitempty"`
	ErrCode  int32     `protobuf:"varint,6,opt,name=ErrCode" json:"ErrCode,omitempty"`
	ErrMsg   string    `protobuf:"bytes,7,opt,name=ErrMsg" json:"ErrMsg,omitempty"`
	UserCode int64     `protobuf:"varint,8,opt,name=UserCode" json:"UserCode,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Event) GetEventId() int64 {
	if m != nil {
		return m.EventId
	}
	return 0
}

func (m *Event) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Event) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *Event) GetMargs() []string {
	if m != nil {
		return m.Margs
	}
	return nil
}

func (m *Event) GetUargs() *Argument {
	if m != nil {
		return m.Uargs
	}
	return nil
}

func (m *Event) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *Event) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *Event) GetUserCode() int64 {
	if m != nil {
		return m.UserCode
	}
	return 0
}

// like a union struct. collect all possible arguments name
type Argument struct {
	FriendNumber  uint32 `protobuf:"varint,1,opt,name=FriendNumber" json:"FriendNumber,omitempty"`
	FriendName    string `protobuf:"bytes,2,opt,name=FriendName" json:"FriendName,omitempty"`
	FriendAddress string `protobuf:"bytes,3,opt,name=FriendAddress" json:"FriendAddress,omitempty"`
	FriendPubkey  string `protobuf:"bytes,4,opt,name=FriendPubkey" json:"FriendPubkey,omitempty"`
	GroupNumber   uint32 `protobuf:"varint,5,opt,name=GroupNumber" json:"GroupNumber,omitempty"`
	GroupTitle    string `protobuf:"bytes,6,opt,name=GroupTitle" json:"GroupTitle,omitempty"`
	GroupIdentity string `protobuf:"bytes,7,opt,name=GroupIdentity" json:"GroupIdentity,omitempty"`
	GroupCookie   string `protobuf:"bytes,8,opt,name=GroupCookie" json:"GroupCookie,omitempty"`
	GroupType     int32  `protobuf:"varint,9,opt,name=GroupType" json:"GroupType,omitempty"`
	PeerNumber    uint32 `protobuf:"varint,10,opt,name=PeerNumber" json:"PeerNumber,omitempty"`
	PeerName      string `protobuf:"bytes,11,opt,name=PeerName" json:"PeerName,omitempty"`
	PeerPubkey    string `protobuf:"bytes,12,opt,name=PeerPubkey" json:"PeerPubkey,omitempty"`
	MsgType       int32  `protobuf:"varint,13,opt,name=MsgType" json:"MsgType,omitempty"`
	Message       string `protobuf:"bytes,14,opt,name=Message" json:"Message,omitempty"`
	IsTyping      int32  `protobuf:"varint,15,opt,name=IsTyping" json:"IsTyping,omitempty"`
	MessageId     uint32 `protobuf:"varint,16,opt,name=MessageId" json:"MessageId,omitempty"`
	Status        int32  `protobuf:"varint,17,opt,name=Status" json:"Status,omitempty"`
	StatusText    string `protobuf:"bytes,18,opt,name=StatusText" json:"StatusText,omitempty"`
	ConnStatus    int32  `protobuf:"varint,19,opt,name=ConnStatus" json:"ConnStatus,omitempty"`
	Nospam        uint32 `protobuf:"varint,20,opt,name=Nospam" json:"Nospam,omitempty"`
	FileNumber    uint32 `protobuf:"varint,21,opt,name=FileNumber" json:"FileNumber,omitempty"`
	FileControl   int32  `protobuf:"varint,22,opt,name=FileControl" json:"FileControl,omitempty"`
	FileIdentity  string `protobuf:"bytes,23,opt,name=FileIdentity" json:"FileIdentity,omitempty"`
	Sent          int32  `protobuf:"varint,24,opt,name=Sent" json:"Sent,omitempty"`
	MimeMsgType   string `protobuf:"bytes,25,opt,name=MimeMsgType" json:"MimeMsgType,omitempty"`
	MimeValue     string `protobuf:"bytes,26,opt,name=MimeValue" json:"MimeValue,omitempty"`
	NextBatch     int64  `protobuf:"varint,27,opt,name=NextBatch" json:"NextBatch,omitempty"`
	PrevBatch     int64  `protobuf:"varint,28,opt,name=PrevBatch" json:"PrevBatch,omitempty"`
}

func (m *Argument) Reset()                    { *m = Argument{} }
func (m *Argument) String() string            { return proto.CompactTextString(m) }
func (*Argument) ProtoMessage()               {}
func (*Argument) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Argument) GetFriendNumber() uint32 {
	if m != nil {
		return m.FriendNumber
	}
	return 0
}

func (m *Argument) GetFriendName() string {
	if m != nil {
		return m.FriendName
	}
	return ""
}

func (m *Argument) GetFriendAddress() string {
	if m != nil {
		return m.FriendAddress
	}
	return ""
}

func (m *Argument) GetFriendPubkey() string {
	if m != nil {
		return m.FriendPubkey
	}
	return ""
}

func (m *Argument) GetGroupNumber() uint32 {
	if m != nil {
		return m.GroupNumber
	}
	return 0
}

func (m *Argument) GetGroupTitle() string {
	if m != nil {
		return m.GroupTitle
	}
	return ""
}

func (m *Argument) GetGroupIdentity() string {
	if m != nil {
		return m.GroupIdentity
	}
	return ""
}

func (m *Argument) GetGroupCookie() string {
	if m != nil {
		return m.GroupCookie
	}
	return ""
}

func (m *Argument) GetGroupType() int32 {
	if m != nil {
		return m.GroupType
	}
	return 0
}

func (m *Argument) GetPeerNumber() uint32 {
	if m != nil {
		return m.PeerNumber
	}
	return 0
}

func (m *Argument) GetPeerName() string {
	if m != nil {
		return m.PeerName
	}
	return ""
}

func (m *Argument) GetPeerPubkey() string {
	if m != nil {
		return m.PeerPubkey
	}
	return ""
}

func (m *Argument) GetMsgType() int32 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

func (m *Argument) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Argument) GetIsTyping() int32 {
	if m != nil {
		return m.IsTyping
	}
	return 0
}

func (m *Argument) GetMessageId() uint32 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *Argument) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Argument) GetStatusText() string {
	if m != nil {
		return m.StatusText
	}
	return ""
}

func (m *Argument) GetConnStatus() int32 {
	if m != nil {
		return m.ConnStatus
	}
	return 0
}

func (m *Argument) GetNospam() uint32 {
	if m != nil {
		return m.Nospam
	}
	return 0
}

func (m *Argument) GetFileNumber() uint32 {
	if m != nil {
		return m.FileNumber
	}
	return 0
}

func (m *Argument) GetFileControl() int32 {
	if m != nil {
		return m.FileControl
	}
	return 0
}

func (m *Argument) GetFileIdentity() string {
	if m != nil {
		return m.FileIdentity
	}
	return ""
}

func (m *Argument) GetSent() int32 {
	if m != nil {
		return m.Sent
	}
	return 0
}

func (m *Argument) GetMimeMsgType() string {
	if m != nil {
		return m.MimeMsgType
	}
	return ""
}

func (m *Argument) GetMimeValue() string {
	if m != nil {
		return m.MimeValue
	}
	return ""
}

func (m *Argument) GetNextBatch() int64 {
	if m != nil {
		return m.NextBatch
	}
	return 0
}

func (m *Argument) GetPrevBatch() int64 {
	if m != nil {
		return m.PrevBatch
	}
	return 0
}

type BaseInfo struct {
	ToxId      string                 `protobuf:"bytes,1,opt,name=ToxId" json:"ToxId,omitempty"`
	Name       string                 `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Stmsg      string                 `protobuf:"bytes,3,opt,name=Stmsg" json:"Stmsg,omitempty"`
	Status     uint32                 `protobuf:"varint,4,opt,name=Status" json:"Status,omitempty"`
	Friends    map[uint32]*FriendInfo `protobuf:"bytes,5,rep,name=Friends" json:"Friends,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Groups     map[uint32]*GroupInfo  `protobuf:"bytes,6,rep,name=Groups" json:"Groups,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ConnStatus int32                  `protobuf:"varint,7,opt,name=ConnStatus" json:"ConnStatus,omitempty"`
	NextBatch  int64                  `protobuf:"varint,8,opt,name=NextBatch" json:"NextBatch,omitempty"`
}

func (m *BaseInfo) Reset()                    { *m = BaseInfo{} }
func (m *BaseInfo) String() string            { return proto.CompactTextString(m) }
func (*BaseInfo) ProtoMessage()               {}
func (*BaseInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BaseInfo) GetToxId() string {
	if m != nil {
		return m.ToxId
	}
	return ""
}

func (m *BaseInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BaseInfo) GetStmsg() string {
	if m != nil {
		return m.Stmsg
	}
	return ""
}

func (m *BaseInfo) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *BaseInfo) GetFriends() map[uint32]*FriendInfo {
	if m != nil {
		return m.Friends
	}
	return nil
}

func (m *BaseInfo) GetGroups() map[uint32]*GroupInfo {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *BaseInfo) GetConnStatus() int32 {
	if m != nil {
		return m.ConnStatus
	}
	return 0
}

func (m *BaseInfo) GetNextBatch() int64 {
	if m != nil {
		return m.NextBatch
	}
	return 0
}

type FriendInfo struct {
	Fnum       uint32 `protobuf:"varint,1,opt,name=Fnum" json:"Fnum,omitempty"`
	Status     uint32 `protobuf:"varint,2,opt,name=Status" json:"Status,omitempty"`
	Pubkey     string `protobuf:"bytes,3,opt,name=Pubkey" json:"Pubkey,omitempty"`
	Name       string `protobuf:"bytes,4,opt,name=Name" json:"Name,omitempty"`
	Stmsg      string `protobuf:"bytes,5,opt,name=Stmsg" json:"Stmsg,omitempty"`
	Avatar     string `protobuf:"bytes,6,opt,name=Avatar" json:"Avatar,omitempty"`
	Seen       uint64 `protobuf:"varint,7,opt,name=Seen" json:"Seen,omitempty"`
	ConnStatus int32  `protobuf:"varint,8,opt,name=ConnStatus" json:"ConnStatus,omitempty"`
}

func (m *FriendInfo) Reset()                    { *m = FriendInfo{} }
func (m *FriendInfo) String() string            { return proto.CompactTextString(m) }
func (*FriendInfo) ProtoMessage()               {}
func (*FriendInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FriendInfo) GetFnum() uint32 {
	if m != nil {
		return m.Fnum
	}
	return 0
}

func (m *FriendInfo) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *FriendInfo) GetPubkey() string {
	if m != nil {
		return m.Pubkey
	}
	return ""
}

func (m *FriendInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FriendInfo) GetStmsg() string {
	if m != nil {
		return m.Stmsg
	}
	return ""
}

func (m *FriendInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *FriendInfo) GetSeen() uint64 {
	if m != nil {
		return m.Seen
	}
	return 0
}

func (m *FriendInfo) GetConnStatus() int32 {
	if m != nil {
		return m.ConnStatus
	}
	return 0
}

type GroupInfo struct {
	Gnum    uint32                 `protobuf:"varint,1,opt,name=Gnum" json:"Gnum,omitempty"`
	Mtype   uint32                 `protobuf:"varint,2,opt,name=Mtype" json:"Mtype,omitempty"`
	GroupId string                 `protobuf:"bytes,3,opt,name=GroupId" json:"GroupId,omitempty"`
	Title   string                 `protobuf:"bytes,4,opt,name=Title" json:"Title,omitempty"`
	Stmsg   string                 `protobuf:"bytes,5,opt,name=Stmsg" json:"Stmsg,omitempty"`
	Ours    bool                   `protobuf:"varint,6,opt,name=Ours" json:"Ours,omitempty"`
	Members map[uint32]*MemberInfo `protobuf:"bytes,7,rep,name=Members" json:"Members,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *GroupInfo) Reset()                    { *m = GroupInfo{} }
func (m *GroupInfo) String() string            { return proto.CompactTextString(m) }
func (*GroupInfo) ProtoMessage()               {}
func (*GroupInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GroupInfo) GetGnum() uint32 {
	if m != nil {
		return m.Gnum
	}
	return 0
}

func (m *GroupInfo) GetMtype() uint32 {
	if m != nil {
		return m.Mtype
	}
	return 0
}

func (m *GroupInfo) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *GroupInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GroupInfo) GetStmsg() string {
	if m != nil {
		return m.Stmsg
	}
	return ""
}

func (m *GroupInfo) GetOurs() bool {
	if m != nil {
		return m.Ours
	}
	return false
}

func (m *GroupInfo) GetMembers() map[uint32]*MemberInfo {
	if m != nil {
		return m.Members
	}
	return nil
}

// = ContactInfo
// 可用于friend,group,peer
type MemberInfo struct {
	Pnum   uint32             `protobuf:"varint,1,opt,name=Pnum" json:"Pnum,omitempty"`
	Pubkey string             `protobuf:"bytes,2,opt,name=Pubkey" json:"Pubkey,omitempty"`
	Name   string             `protobuf:"bytes,3,opt,name=Name" json:"Name,omitempty"`
	Mtype  MemberInfo_MemType `protobuf:"varint,4,opt,name=Mtype,enum=thspbs.MemberInfo_MemType" json:"Mtype,omitempty"`
}

func (m *MemberInfo) Reset()                    { *m = MemberInfo{} }
func (m *MemberInfo) String() string            { return proto.CompactTextString(m) }
func (*MemberInfo) ProtoMessage()               {}
func (*MemberInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *MemberInfo) GetPnum() uint32 {
	if m != nil {
		return m.Pnum
	}
	return 0
}

func (m *MemberInfo) GetPubkey() string {
	if m != nil {
		return m.Pubkey
	}
	return ""
}

func (m *MemberInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MemberInfo) GetMtype() MemberInfo_MemType {
	if m != nil {
		return m.Mtype
	}
	return MemberInfo_UNKNOWN
}

type Message struct {
	MsgId   uint64      `protobuf:"varint,1,opt,name=MsgId" json:"MsgId,omitempty"`
	Content string      `protobuf:"bytes,2,opt,name=Content" json:"Content,omitempty"`
	Peer    *MemberInfo `protobuf:"bytes,3,opt,name=Peer" json:"Peer,omitempty"`
	Created uint64      `protobuf:"varint,4,opt,name=Created" json:"Created,omitempty"`
	Updated uint64      `protobuf:"varint,5,opt,name=Updated" json:"Updated,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Message) GetMsgId() uint64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *Message) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Message) GetPeer() *MemberInfo {
	if m != nil {
		return m.Peer
	}
	return nil
}

func (m *Message) GetCreated() uint64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Message) GetUpdated() uint64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type Messages struct {
	Msgs []*Message `protobuf:"bytes,1,rep,name=Msgs" json:"Msgs,omitempty"`
}

func (m *Messages) Reset()                    { *m = Messages{} }
func (m *Messages) String() string            { return proto.CompactTextString(m) }
func (*Messages) ProtoMessage()               {}
func (*Messages) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Messages) GetMsgs() []*Message {
	if m != nil {
		return m.Msgs
	}
	return nil
}

type EmptyReq struct {
}

func (m *EmptyReq) Reset()                    { *m = EmptyReq{} }
func (m *EmptyReq) String() string            { return proto.CompactTextString(m) }
func (*EmptyReq) ProtoMessage()               {}
func (*EmptyReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type HelloReq struct {
	Name string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=Msg" json:"Msg,omitempty"`
}

func (m *HelloReq) Reset()                    { *m = HelloReq{} }
func (m *HelloReq) String() string            { return proto.CompactTextString(m) }
func (*HelloReq) ProtoMessage()               {}
func (*HelloReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *HelloReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HelloReq) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type HelloResp struct {
	Code   int32 `protobuf:"varint,1,opt,name=Code" json:"Code,omitempty"`
	Status int64 `protobuf:"varint,2,opt,name=Status" json:"Status,omitempty"`
}

func (m *HelloResp) Reset()                    { *m = HelloResp{} }
func (m *HelloResp) String() string            { return proto.CompactTextString(m) }
func (*HelloResp) ProtoMessage()               {}
func (*HelloResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *HelloResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *HelloResp) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*Event)(nil), "thspbs.Event")
	proto.RegisterType((*Argument)(nil), "thspbs.Argument")
	proto.RegisterType((*BaseInfo)(nil), "thspbs.BaseInfo")
	proto.RegisterType((*FriendInfo)(nil), "thspbs.FriendInfo")
	proto.RegisterType((*GroupInfo)(nil), "thspbs.GroupInfo")
	proto.RegisterType((*MemberInfo)(nil), "thspbs.MemberInfo")
	proto.RegisterType((*Message)(nil), "thspbs.Message")
	proto.RegisterType((*Messages)(nil), "thspbs.Messages")
	proto.RegisterType((*EmptyReq)(nil), "thspbs.EmptyReq")
	proto.RegisterType((*HelloReq)(nil), "thspbs.HelloReq")
	proto.RegisterType((*HelloResp)(nil), "thspbs.HelloResp")
	proto.RegisterEnum("thspbs.MemberInfo_MemType", MemberInfo_MemType_name, MemberInfo_MemType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Toxhs service

type ToxhsClient interface {
	PollCallback(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (Toxhs_PollCallbackClient, error)
	GetBaseInfo(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*BaseInfo, error)
	RmtCall(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Event, error)
	Ping(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*EmptyReq, error)
}

type toxhsClient struct {
	cc *grpc.ClientConn
}

func NewToxhsClient(cc *grpc.ClientConn) ToxhsClient {
	return &toxhsClient{cc}
}

func (c *toxhsClient) PollCallback(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (Toxhs_PollCallbackClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Toxhs_serviceDesc.Streams[0], c.cc, "/thspbs.Toxhs/PollCallback", opts...)
	if err != nil {
		return nil, err
	}
	x := &toxhsPollCallbackClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Toxhs_PollCallbackClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type toxhsPollCallbackClient struct {
	grpc.ClientStream
}

func (x *toxhsPollCallbackClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *toxhsClient) GetBaseInfo(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*BaseInfo, error) {
	out := new(BaseInfo)
	err := grpc.Invoke(ctx, "/thspbs.Toxhs/GetBaseInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toxhsClient) RmtCall(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Event, error) {
	out := new(Event)
	err := grpc.Invoke(ctx, "/thspbs.Toxhs/RmtCall", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toxhsClient) Ping(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*EmptyReq, error) {
	out := new(EmptyReq)
	err := grpc.Invoke(ctx, "/thspbs.Toxhs/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Toxhs service

type ToxhsServer interface {
	PollCallback(*EmptyReq, Toxhs_PollCallbackServer) error
	GetBaseInfo(context.Context, *EmptyReq) (*BaseInfo, error)
	RmtCall(context.Context, *Event) (*Event, error)
	Ping(context.Context, *EmptyReq) (*EmptyReq, error)
}

func RegisterToxhsServer(s *grpc.Server, srv ToxhsServer) {
	s.RegisterService(&_Toxhs_serviceDesc, srv)
}

func _Toxhs_PollCallback_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmptyReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ToxhsServer).PollCallback(m, &toxhsPollCallbackServer{stream})
}

type Toxhs_PollCallbackServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type toxhsPollCallbackServer struct {
	grpc.ServerStream
}

func (x *toxhsPollCallbackServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

func _Toxhs_GetBaseInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToxhsServer).GetBaseInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/thspbs.Toxhs/GetBaseInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToxhsServer).GetBaseInfo(ctx, req.(*EmptyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Toxhs_RmtCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToxhsServer).RmtCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/thspbs.Toxhs/RmtCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToxhsServer).RmtCall(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

func _Toxhs_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToxhsServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/thspbs.Toxhs/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToxhsServer).Ping(ctx, req.(*EmptyReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Toxhs_serviceDesc = grpc.ServiceDesc{
	ServiceName: "thspbs.Toxhs",
	HandlerType: (*ToxhsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBaseInfo",
			Handler:    _Toxhs_GetBaseInfo_Handler,
		},
		{
			MethodName: "RmtCall",
			Handler:    _Toxhs_RmtCall_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Toxhs_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PollCallback",
			Handler:       _Toxhs_PollCallback_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ths.proto",
}

// Client API for Greeter service

type GreeterClient interface {
	SayHello(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*HelloReq, error)
	// 测试带参数的hello
	SayHellox(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloReq, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*HelloReq, error) {
	out := new(HelloReq)
	err := grpc.Invoke(ctx, "/thspbs.Greeter/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SayHellox(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloReq, error) {
	out := new(HelloReq)
	err := grpc.Invoke(ctx, "/thspbs.Greeter/SayHellox", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Greeter service

type GreeterServer interface {
	SayHello(context.Context, *EmptyReq) (*HelloReq, error)
	// 测试带参数的hello
	SayHellox(context.Context, *HelloReq) (*HelloReq, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/thspbs.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*EmptyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SayHellox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHellox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/thspbs.Greeter/SayHellox",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHellox(ctx, req.(*HelloReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "thspbs.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
		{
			MethodName: "SayHellox",
			Handler:    _Greeter_SayHellox_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ths.proto",
}

func init() { proto.RegisterFile("ths.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xcd, 0x72, 0xe3, 0x44,
	0x10, 0x46, 0xb6, 0x64, 0xcb, 0xed, 0xcd, 0xae, 0x77, 0x08, 0x41, 0x98, 0xb0, 0xe5, 0x12, 0xd4,
	0xae, 0x8b, 0x83, 0x37, 0x1b, 0xa8, 0xca, 0x16, 0xb7, 0x6c, 0x70, 0x82, 0x0b, 0xe2, 0xb8, 0x26,
	0x09, 0x9c, 0x95, 0xf5, 0xe0, 0x98, 0xc8, 0x92, 0x57, 0x33, 0x4e, 0xc5, 0x0f, 0xc2, 0x81, 0x87,
	0xe0, 0xcc, 0x9d, 0x03, 0x6f, 0xc0, 0x7b, 0xf0, 0x08, 0x54, 0xf7, 0xcc, 0x48, 0xf2, 0x0f, 0x5b,
	0xc5, 0x6d, 0xbe, 0xaf, 0xa7, 0x7b, 0x7a, 0xba, 0x7b, 0x3e, 0x09, 0x1a, 0xea, 0x56, 0xf6, 0xe6,
	0x59, 0xaa, 0x52, 0x56, 0x53, 0xb7, 0x72, 0x7e, 0x23, 0xc3, 0xbf, 0x1d, 0xf0, 0xfa, 0xf7, 0x22,
	0x51, 0x2c, 0x80, 0x3a, 0x2d, 0x06, 0xe3, 0xc0, 0xe9, 0x38, 0xdd, 0x2a, 0xb7, 0x90, 0x31, 0x70,
	0x87, 0xd1, 0x4c, 0x04, 0x95, 0x8e, 0xd3, 0x6d, 0x70, 0x5a, 0x23, 0x77, 0x9c, 0x4d, 0x64, 0x50,
	0xed, 0x54, 0x91, 0xc3, 0x35, 0xdb, 0x05, 0xef, 0x3c, 0x42, 0xd2, 0x25, 0x52, 0x03, 0xf6, 0x1c,
	0xbc, 0x6b, 0x62, 0xbd, 0x8e, 0xd3, 0x6d, 0x1e, 0xb6, 0x7a, 0xfa, 0xe4, 0xde, 0x71, 0x36, 0x59,
	0xcc, 0x44, 0xa2, 0xb8, 0x36, 0xd3, 0xf9, 0x59, 0x76, 0x92, 0x8e, 0x45, 0x50, 0xeb, 0x38, 0x5d,
	0x8f, 0x5b, 0xc8, 0xf6, 0xa0, 0xd6, 0xcf, 0xb2, 0x73, 0x39, 0x09, 0xea, 0x94, 0x81, 0x41, 0xac,
	0x0d, 0xfe, 0xb5, 0x14, 0xda, 0xc5, 0xa7, 0x94, 0x73, 0x1c, 0xfe, 0x53, 0x03, 0xdf, 0x9e, 0xc0,
	0x42, 0x78, 0x74, 0x9a, 0x4d, 0x45, 0x32, 0x1e, 0x2e, 0x66, 0x37, 0x22, 0xa3, 0xfb, 0xed, 0xf0,
	0x15, 0x8e, 0x3d, 0x03, 0x30, 0xb8, 0xb8, 0x6a, 0x89, 0x61, 0x5f, 0xc0, 0x8e, 0x46, 0xc7, 0xe3,
	0x71, 0x26, 0x24, 0xde, 0x1c, 0xb7, 0xac, 0x92, 0xc5, 0x49, 0xa3, 0xc5, 0xcd, 0x9d, 0x58, 0x06,
	0x2e, 0x6d, 0x5a, 0xe1, 0x58, 0x07, 0x9a, 0x67, 0x59, 0xba, 0x98, 0x9b, 0x64, 0x3c, 0x4a, 0xa6,
	0x4c, 0x61, 0x2e, 0x04, 0xaf, 0xa6, 0x2a, 0xd6, 0xd5, 0x68, 0xf0, 0x12, 0x83, 0xb9, 0x10, 0x1a,
	0x8c, 0x45, 0xa2, 0xa6, 0x6a, 0x69, 0xea, 0xb2, 0x4a, 0xe6, 0xe7, 0x9c, 0xa4, 0xe9, 0xdd, 0x54,
	0x57, 0xa8, 0xc1, 0xcb, 0x14, 0xdb, 0x87, 0x86, 0x8e, 0xba, 0x9c, 0x8b, 0xa0, 0x41, 0x45, 0x2f,
	0x08, 0xcc, 0x62, 0x24, 0x44, 0x66, 0xd2, 0x04, 0x4a, 0xb3, 0xc4, 0x60, 0xf9, 0x09, 0x61, 0xbd,
	0x9a, 0x14, 0x3c, 0xc7, 0xd6, 0xd7, 0x54, 0xe1, 0x91, 0xbe, 0x41, 0xc1, 0x60, 0xb3, 0xcf, 0xe5,
	0x84, 0xce, 0xdd, 0xd1, 0xcd, 0x36, 0x90, 0x2c, 0x42, 0xca, 0x68, 0x22, 0x82, 0xc7, 0xe4, 0x66,
	0x21, 0x9e, 0x37, 0x90, 0x57, 0xcb, 0xf9, 0x34, 0x99, 0x04, 0x4f, 0xc8, 0x29, 0xc7, 0x78, 0x13,
	0xb3, 0x6d, 0x30, 0x0e, 0x5a, 0x94, 0x6a, 0x41, 0xe0, 0x00, 0x5d, 0xaa, 0x48, 0x2d, 0x64, 0xf0,
	0x94, 0xfc, 0x0c, 0xc2, 0x2c, 0xf5, 0xea, 0x4a, 0x3c, 0xa8, 0x80, 0xe9, 0x2c, 0x0b, 0x06, 0xed,
	0x27, 0x69, 0x92, 0x18, 0xdf, 0x0f, 0xc9, 0xb7, 0xc4, 0x60, 0xdc, 0x61, 0x2a, 0xe7, 0xd1, 0x2c,
	0xd8, 0xa5, 0x23, 0x0d, 0xa2, 0x59, 0x9a, 0xc6, 0xc2, 0x54, 0xee, 0x23, 0x5d, 0xb9, 0x82, 0xc1,
	0xce, 0x20, 0x3a, 0x49, 0x13, 0x95, 0xa5, 0x71, 0xb0, 0x47, 0x81, 0xcb, 0x14, 0xcd, 0xd1, 0x34,
	0x16, 0x79, 0x83, 0x3f, 0x36, 0x73, 0x54, 0xe2, 0xf0, 0x09, 0x5e, 0x8a, 0x44, 0x05, 0x01, 0xb9,
	0xd3, 0x1a, 0x23, 0x9f, 0x4f, 0x67, 0xc2, 0xd6, 0xf6, 0x13, 0xdd, 0xf3, 0x12, 0x45, 0x95, 0x9a,
	0xce, 0xc4, 0x8f, 0x51, 0xbc, 0x10, 0x41, 0x9b, 0xec, 0x05, 0x81, 0xd6, 0xa1, 0x78, 0x50, 0x6f,
	0x22, 0xf5, 0xf6, 0x36, 0xf8, 0x94, 0xde, 0x54, 0x41, 0xa0, 0x75, 0x94, 0x89, 0x7b, 0x6d, 0xdd,
	0xd7, 0xd6, 0x9c, 0x08, 0x7f, 0xaf, 0x82, 0xff, 0x26, 0x92, 0x62, 0x90, 0xfc, 0x9c, 0xa2, 0x16,
	0x5c, 0xa5, 0x0f, 0x46, 0x4b, 0x1a, 0x5c, 0x83, 0xad, 0x4a, 0xb2, 0x0b, 0xde, 0xa5, 0x9a, 0xc9,
	0x89, 0x79, 0x50, 0x1a, 0x94, 0x5a, 0xe6, 0xea, 0xd2, 0x9a, 0x92, 0x1f, 0x41, 0x5d, 0x3f, 0x26,
	0xd4, 0x93, 0x6a, 0xb7, 0x79, 0xf8, 0x99, 0xd5, 0x13, 0x7b, 0x74, 0xcf, 0xd8, 0xfb, 0x89, 0xca,
	0x96, 0xdc, 0xee, 0x66, 0x5f, 0x43, 0x8d, 0x46, 0x5b, 0x06, 0x35, 0xf2, 0xdb, 0xdf, 0xf0, 0xd3,
	0x66, 0xed, 0x66, 0xf6, 0xae, 0x4d, 0x40, 0x7d, 0x63, 0x02, 0x56, 0xea, 0xe5, 0xaf, 0xd5, 0xab,
	0x3d, 0xb4, 0x6a, 0xa0, 0xa3, 0xb2, 0x16, 0x54, 0xf1, 0x39, 0x68, 0xf9, 0xc1, 0x25, 0xeb, 0x82,
	0x77, 0x4f, 0x9d, 0xa8, 0x90, 0x38, 0x32, 0x9b, 0x94, 0x76, 0xc3, 0xb4, 0xb8, 0xde, 0xf0, 0x4d,
	0xe5, 0xb5, 0xd3, 0xfe, 0xc1, 0xbc, 0xe8, 0xff, 0x0c, 0xf7, 0x62, 0x35, 0xdc, 0x53, 0x1b, 0x4e,
	0x0b, 0xc3, 0x6a, 0xb4, 0xf0, 0x2f, 0xc7, 0x4a, 0x1e, 0x75, 0x8c, 0x81, 0x7b, 0x9a, 0x2c, 0x66,
	0x26, 0x1c, 0xad, 0x4b, 0x5d, 0xa8, 0xac, 0x74, 0x61, 0x0f, 0x6a, 0xe6, 0x69, 0xeb, 0xa6, 0x19,
	0x94, 0xf7, 0xd7, 0xdd, 0xd6, 0x5f, 0x6f, 0xad, 0xbf, 0xc7, 0xf7, 0x91, 0x8a, 0x32, 0x23, 0x6f,
	0x06, 0xe9, 0xa1, 0x16, 0x09, 0x95, 0xda, 0xe5, 0xb4, 0x5e, 0x6b, 0x82, 0xbf, 0xde, 0x84, 0xf0,
	0xb7, 0x8a, 0xd1, 0x31, 0x7b, 0x8f, 0xb3, 0xd2, 0x3d, 0x70, 0x4d, 0x5f, 0x26, 0x85, 0x0f, 0x42,
	0x5f, 0x43, 0x03, 0x94, 0x1a, 0xa3, 0x98, 0xe6, 0x1a, 0x16, 0xd2, 0xf4, 0x92, 0xf6, 0xba, 0x66,
	0x7a, 0x49, 0x76, 0xb7, 0xdf, 0x84, 0x81, 0x7b, 0xb1, 0xc8, 0x24, 0xdd, 0xc3, 0xe7, 0xb4, 0x66,
	0xaf, 0x51, 0xc4, 0xf0, 0xa9, 0xe3, 0xcc, 0xe0, 0xb4, 0x3d, 0xdb, 0xe8, 0x44, 0xcf, 0x6c, 0x30,
	0x63, 0x6a, 0x10, 0x8e, 0x4c, 0xd9, 0xf0, 0x3f, 0x46, 0x46, 0xbb, 0xad, 0x37, 0xf9, 0x0f, 0x07,
	0xa0, 0xb0, 0x60, 0xb2, 0xa3, 0x52, 0x71, 0x46, 0xa6, 0xc9, 0xa6, 0x99, 0x95, 0xad, 0xcd, 0xac,
	0x96, 0x9a, 0x79, 0x60, 0x0b, 0x89, 0x85, 0x79, 0x7c, 0xd8, 0xde, 0x3c, 0x1c, 0x97, 0x28, 0x34,
	0xa6, 0xc8, 0xe1, 0x11, 0x95, 0x82, 0xa4, 0xa7, 0x09, 0xf5, 0xeb, 0xe1, 0xf7, 0xc3, 0x8b, 0x9f,
	0x86, 0xad, 0x0f, 0x18, 0x40, 0xed, 0x94, 0x0f, 0xfa, 0xc3, 0x6f, 0x5b, 0x0e, 0x6b, 0x80, 0x77,
	0xc6, 0x2f, 0xae, 0x47, 0xad, 0x0a, 0xf3, 0xc1, 0x1d, 0xf5, 0xfb, 0xbc, 0x55, 0x0d, 0x7f, 0x75,
	0xf2, 0x2f, 0x01, 0xf5, 0x4f, 0x4e, 0x8c, 0x9a, 0xb8, 0x5c, 0x03, 0xec, 0x1f, 0xea, 0x25, 0x6a,
	0xa0, 0xce, 0xdc, 0x42, 0xf6, 0x1c, 0x5c, 0xfc, 0xd8, 0x50, 0xea, 0xdb, 0x4b, 0x44, 0x76, 0x8a,
	0x90, 0x89, 0x48, 0x89, 0x31, 0x5d, 0xc8, 0xe5, 0x16, 0xa2, 0xe5, 0x7a, 0x3e, 0x26, 0x8b, 0xa7,
	0x2d, 0x06, 0x86, 0x2f, 0xc1, 0x37, 0x69, 0x49, 0xf6, 0x39, 0xb8, 0xe7, 0x72, 0x22, 0x03, 0x87,
	0x9a, 0xfc, 0xa4, 0x38, 0x87, 0xec, 0x9c, 0x8c, 0x21, 0x80, 0xdf, 0x9f, 0xcd, 0xd5, 0x92, 0x8b,
	0x77, 0xe1, 0x01, 0xf8, 0xdf, 0x89, 0x38, 0x4e, 0xb9, 0x78, 0x97, 0xd7, 0xd7, 0x29, 0xd5, 0xb7,
	0x05, 0x55, 0xfc, 0xcf, 0xd1, 0xd7, 0xc1, 0x65, 0x78, 0x04, 0x0d, 0xe3, 0x21, 0xe7, 0xe8, 0x42,
	0x7f, 0x3b, 0x8e, 0x96, 0x7c, 0xfb, 0x77, 0x54, 0x7a, 0xa3, 0x55, 0xfb, 0x46, 0x0f, 0xff, 0x74,
	0x48, 0x82, 0x6f, 0x25, 0x7b, 0x05, 0x8f, 0x46, 0x69, 0x1c, 0x9f, 0x44, 0x71, 0x7c, 0x13, 0xbd,
	0xbd, 0x63, 0xf9, 0x2f, 0x98, 0x4d, 0xab, 0xbd, 0x93, 0x33, 0xf8, 0xcb, 0x77, 0xe0, 0xb0, 0x57,
	0xd0, 0x3c, 0x13, 0x2a, 0x57, 0xf3, 0x4d, 0x8f, 0xd6, 0xba, 0x7c, 0xb2, 0x17, 0x50, 0xe7, 0x33,
	0x85, 0x87, 0xb0, 0xd5, 0x70, 0x6b, 0xd1, 0xd9, 0x97, 0xe0, 0x8e, 0xf0, 0x9b, 0xfd, 0x9e, 0xa0,
	0x96, 0x39, 0xfc, 0x05, 0x9f, 0xa8, 0x10, 0x4a, 0x64, 0xac, 0x07, 0xfe, 0x65, 0xb4, 0xa4, 0x5a,
	0xbc, 0xcf, 0x35, 0x2f, 0xef, 0x4b, 0x68, 0xd8, 0xfd, 0x0f, 0x6c, 0xc3, 0xbc, 0xe9, 0x70, 0x53,
	0xa3, 0x3f, 0xe3, 0xaf, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xbd, 0x54, 0x45, 0x45, 0x26, 0x0b,
	0x00, 0x00,
}
